# Use a lightweight Nginx image
FROM nginx:alpine

# Copy the contents of the frontend project to the default Nginx public directory
COPY . /usr/share/nginx/html

# Expose the default Nginx port
EXPOSE 80