"""modelo localization

Revision ID: bec10c6ddfa8
Revises: b6b39d8df73c
Create Date: 2023-11-30 12:45:11.082200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bec10c6ddfa8'
down_revision: Union[str, None] = 'b6b39d8df73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('localization')
    # ### end Alembic commands ###
